
** Template

#+BEGIN_HTML
---
layout: default
title: 
categories:
---
#+END_HTML

There is a worg tutorial.

** Resolution: write more
:PROPERTIES:
:EXPORT_FILE_NAME: 2015-01-07-stat-diary1
:END:

# This has no effect:

#+title: Resolution: write more

#+BEGIN_HTML
---
title: I resolve to write more
layout: default
categories: 
---
#+END_HTML

#+BEGIN_QUOTE
[[http://andrewgelman.com/2015/01/07/2015-statistics-diary][You should all keep statistics diaries.]]
#+END_QUOTE

Yes sir.

#+BEGIN_QUOTE
... statistical topics are usually less private. Indeed, even when a
topic is highly personal, a statistical framing can provide some
comfortable emotional distance.
#+END_QUOTE

I hadn't considered that before, but it makes sense.

Writing entries in org-mode should streamline things.
Clumsy aspect: have to manually reexport and commit output file.
Untitled sections show up as a plain pound sign when exported from
org-mode to markdown.

*** 

Timestamps.
They alter indentation/paragraph flow.
Or do they?
[2015-01-07 15:25]

*** The default font size for headings is gigantic.

Also they make things more complicated.
