
# Template:   (See also worg tutorial)
** 

#+BEGIN_HTML
---
layout: default
title: 
categories:
---
#+END_HTML

** Resolution: write more                                             :blog:
:PROPERTIES:
:EXPORT_FILE_NAME: 2015-01-07-stat-diary1
:END:

# This has no effect:

#+title: Resolution: write more

#+BEGIN_HTML
---
title: I resolve to write more
layout: default
categories: 
---
#+END_HTML

#+BEGIN_QUOTE
[[http://andrewgelman.com/2015/01/07/2015-statistics-diary][You should all keep statistics diaries.]]
#+END_QUOTE

Yes sir.

#+BEGIN_QUOTE
... statistical topics are usually less private. Indeed, even when a
topic is highly personal, a statistical framing can provide some
comfortable emotional distance.
#+END_QUOTE

I hadn't considered that before, but it makes sense.

Writing entries in org-mode should streamline things.
Clumsy aspect: have to manually reexport and commit output file.
Untitled sections show up as a plain pound sign when exported from
org-mode to markdown.

*** 

Timestamps.
They alter indentation/paragraph flow.
Or do they?
[2015-01-07 15:25]
I guess not.

*** The default font size for headings is gigantic.

Also they make things more complicated.

** Write in diary less, introduction more
#+BEGIN_HTML
---
layout: default
title: 
categories:
---
#+END_HTML

Dear statistical diary,

Sudden influx of Karl Broman posts.
Was there something funny with his RSS feed or Gwene?
Anyway, motivation to work on
[[https://kbroman.wordpress.com/2014/12/03/the-value-of-thesis-introdiscussion/][lit review]].
# [[gnus:gwene.com.wordpress.kbroman.stupidestthing#x1-K%2BvWKSv93EKq5mNNXiT8sN71rZY@gwene.org][Post by Karl Broman: Initial steps ...]]
# [[gnus:gwene.com.wordpress.kbroman.stupidestthing#x1-AyrUitd1oEUWCRP02u6aADQqiXM@gwene.org][Post from Karl Broman: The value of thesis intro]]
I like Karl's phrase:
'Ye Olde Standard Computational Science Practice'.
Picturing early computational scientists with tricornered hats ringing bells.
(They use emacs, of course).

Technology grating, as usual.
RSS and email clients.
Journal websites.
(Repeated clicks to get to full text,
versioning/failure to retypeset articles after correction.)
Extra clicks to get to
Lubinski et al. (next link)
supplemental material
via an issue-wide page!
Ye Olde Web Technology?

OK, I should get to work.
Need to provide some return on the
[[http://andrewgelman.com/2015/01/08/life-paths-accomplishments-mathematically-precocious-males-females-four-decades-later/][federal investment]]
in my research and education.

[2015-01-08 08:43]
[2015-01-08 09:00]

** Thinking out loud (teaching)

Dear statistical waitress,

Andrew today:
"I’m going to go lighter on the traditional sampling topics (ratio
and regression estimation, stratified cluster sampling bla bla bla)
and instead have them do Mister P for real in R and Stan, just like
the grownups do."

"No fear of dead time."
Savor the awkward pauses!
Same advice that STM gave for running paper discussions.
Sort of.

Just why exactly does he like Stan so much?

What standardized test score data is publicly available?
SAT data in The Sleuth.

Reading ARM this morning.
"... literature is full of confusing and contradictory advice."
[2015-01-09 09:56]

I should really take time to enjoy stats,
not worry so much about accomplishing things.

** Trying to use org-babel.  Give up for now.
:LOGBOOK:  
CLOCK: [2015-01-10 Sat 12:53]--[2015-01-10 Sat 13:16] =>  0:23
:END:      

#+BEGIN_SRC R :exports both :file figure.png
x <- 1:10
plot(x)
#+END_SRC

Hmm.  I don't like the org-babel documentation today.

Why do I need the TIKz device?

R-pie example says:
Error: could not find function ".ess.eval"
Problem with ESS changes?

[[info:org#Working with source code]]
[[info:org#Structure of code blocks]]


** Article on Brad Perez (Potti lab researcher)

New details on the Potti case published yesterday in The Cancer Letter.
I agree with Arthur Caplan:
“The medical student was very brave. That was quite an act of courage."
# I didn't realize he had moved.

Strong words from Donald Berry:
 ‘Commenting on education, the problem is really who are the
 educators. The senior scientists are the problem. They are not the
 solution. And...young statisticians are just as clueless as the
 senior scientists.’

*** Misc

"The memo shows that, by ignoring the content of the Perez memo,
Duke’s deans allowed Nevins to investigate his protégé himself."
Which protégé?  Potti?

Cancer Letter site annoying (big flash videos, ads), and article spread
across four pages.  Clean up and combine.
Don't understand scripts in header,
or what causes the big non-loading nonlinking block.

Static Header: delete entire thing.
portletBodyHTML has much junk.
Delete big issuu iframes.  I see now that they were intended to be
embedded documents.  Whatever.

** Rereading

Reread Bob's post on Michael Jordan interview article.
Sounds like the journalist did everything they should.

Revisit The Statistical Significance Filter: If an estimate is
statistically significant, it’s probably an overestimate.
(Gelman and Weakliem 2009).
Confusing language elsewhere: "necessarily an overestimate".
I don't remember where.

** "it’s hard to work intensely"
[2015-01-11 17:04]

Poincaré.

shepik commented on May 12, 2012

"I love it that you can easily know just by
looking at word wraps of the comment
whether a person is supporting Linus or not


Andrew says:
"And all this “statistically significant but not practically
significant” talk can completely lead us astray, by leading us to be
wary of very small estimates, while what we should really be
suspicious of, is very large estimates!"

Makes sense.

[2015-01-12 10:26]

** RSS                                                                :blog:
:PROPERTIES:
:EXPORT_FILE_NAME: 2015-02-03-rss
:END:
# Not strictly necessary, but shows up as Rss otherwise
#+BEGIN_HTML
---
layout: default
title: RSS
categories: whining
---
#+END_HTML

I am sorry that I don't have an RSS feed.
I like RSS as a technology.

I like Gwene,
but a problem is going to send me to thunderbird
: A feed with this internal ID (http://www.sciencedirect.com) is already subscribed as gwene.com.sciencedirect.ecological.modeling.latest.content.

Like this page:
https://openaccessbutton.org/advocacy

** Fossil 1.3.1                                                       :blog:
:PROPERTIES:
:EXPORT_FILE_NAME: 2015-02-23-fossil
:END:

version 1.3.1 just released.

http://fossil-scm.org/index.html/info/a56f58299c04bdf2

I agree that git is a bad fit for scientists.
Learning fossil has been too much fun---it's distracting!

Full list: http://fossil-scm.org/index.html/doc/trunk/www/quotes.wiki

More serious: http://fossil-scm.org/index.html/doc/trunk/www/fossil-v-git.wiki

Related: recent complaints about jekyll on twitter.
I will reserve my complaints for markdown itself.
Org export converted my 'v.' for version above to a '1.'.
I would tag this post 'whining',
but that would take too much effort.

** Don't enforce Git or GitHub as a standard                          :blog:
:PROPERTIES:
:EXPORT_FILE_NAME: 2015-04-21-anti-git
:END:

#+BEGIN_HTML
---
layout: default
title: Don't enforce Git or GitHub as a standard
categories: whining
---
#+END_HTML

Post title named after recent post where /x/ = =R=
that various ecologists linked to.
See links in previous post.
See also the random git man page generator.
See also the emacs listserve
for some really hilarious comments
by intelligent people (e.g. RMS)
trying to understand strange and subtle git terminology.

Irony of centralization yadda yadda yadda...

DO enforce ISO 8601 as a standard.

** Magit 1.2.0                                                        :blog:
:PROPERTIES:
:EXPORT_FILE_NAME: 2015-08-13-magit-2
:END:

New release (user interface largely the same),
and the fact that Junio Hamano is
(or at least used to be)
a devoted TWiV listener and [[https://disqus.com/by/juniochamano][commenter]]
makes me feel some goodwill toward Git.

Disqus is turning into a bit of a time suck.

** Git 2.5.0
:PROPERTIES:
:EXPORT_FILE_NAME: 2015-08-23-git-2_5
:END:
#+BEGIN_HTML
---
title: Git 2.5.0
layout: default
categories: 
---
#+END_HTML

It took me a while to notice this.
I am surprised that I am actually excited
about the new =git worktree= command.
The ease of starting new checkouts
was one of the primary reasons
I started to prefer fossil over git this year.

** ShinyStan 2.0.0
[2015-08-14 12:51]

** R 3.2.2
[2015-08-22 Sat]

** Firefox 40ish

Does anyone else find the 'Library' window
to be so slow as to be unusable?
HealthReport tells me that I have
~14000 bookmarks
and ~32000 lines in my places database table.

** Fossil 2.0
:PROPERTIES:
:EXPORT_FILE_NAME: 2015-03-01-fossil-2
:END:

Just an idea for now.
I don't have anything to say about this now.
Just want a post with this title.

** TODO org export without timestamps
